title: Блог Александра Бизикова
description: "Привет, меня зовут Александр Бизиков. Я знаю HTML, CSS, JavaScript. Верстаю сайты, делаю темы для Wordpress. Люблю фотографировать, работаю веб-разработчиком в i-Sys."
version: 2.5
url: http://bizikov.github.io/bizikov.ru/
locale: ru_RU

css:
  - /assets/css/style.css

avatar: /upload/page/home/me.jpg
favicon: /favicon.ico

fb_admins: http://facebook.com/bizikov
fb_appid: 337414769782635
vk_appid: 2126013

feed: http://feeds.feedburner.com/bizikov
twitter: bizi

header_menu:
  - title: Главная
    url: /
  - title: Заметки
    url: /archive/
  - title: Теги
    url: /tags/
  - title: О себе
    url: /about/
  - title: РСС
    url: http://feeds.feedburner.com/bizikov

permalink:   /:categories/:year/:month/:title/
timezone:    Asia/Yerevan
future:      true
highlighter: pygments
markdown:    kramdown
kramdown:
  auto_ids: false

