name: Александр Бизиков
description: Пишу об интересных и полезных для меня материалах
disqus_shortname: bizikov
version: 2.4
#url: http://localhost:4000
url: http://bizikov.ru

# Ссылки для навигации
links:
  - title: Главная
    url: /
  - title: Заметки
    url: /archive/
  - title: Теги
    url: /tags/
  - title: О себе
    url: /about/

# Ссылки на социальные сети
social:
  Инстаграм: http://instagram.com/bizikov
  Твиттер: https://twitter.com/bizi
  Вконтакте: http://vk.com/bizikov
  Фэйсбук:  https://facebook.com/bizikov
  Гугл плюс: https://plus.google.com/+AlexandrBizikov
  Яндекс.Фотки: http://fotki.yandex.ru/users/alexandr-bizikov/
  Кинопоиск: http://www.kinopoisk.ru/user/1129585/
  Мои сериалы: http://myshows.ru/bizikov
  Мои книги: http://bibla.ru/Bizi/
  Фликр: http://www.flickr.com/photos/48363663@N05/
  Пинтерест: http://pinterest.com/bizikov/
  Форсквер: https://ru.foursquare.com/bizi
  Ютуб: https://www.youtube.com/user/Bizikov
  ЖЖЖ: http://bizikov.livejournal.com/
  Хабр: http://habrahabr.ru/users/bizikov/
  Вайн: https://vine.co/u/906514742397517824
  Вимео: http://vimeo.com/bizikov

permalink: /:categories/:year/:month/:title/

timezone:    Asia/Yerevan
future:      true
pygments:    true
markdown:    kramdown
kramdown:
  auto_ids: false

copyright: "&copy; 2009 — 2014, Александр Бизиков."
