name: Блог Александра Бизикова
description: "Привет, меня зовут Александр Бизиков. Я знаю HTML, CSS, JavaScript. Верстаю сайты, делаю темы для Wordpress. Люблю фотографировать, работаю веб-разработчиком в i-Sys."
version: 2.5
#url: http://localhost:4000
url: http://bizikov.ru

css:
  - /assets/css/style.css

avatar: /upload/page/home/me.jpg
favicon: /favicon.ico

feed: http://feeds.feedburner.com/bizikov

header_menu:
  - title: Главная
    url: /
  - title: Заметки
    url: /archive/
  - title: Теги
    url: /tags/
  - title: О себе
    url: /about/
  - title: РСС
    url: /feed.xml

permalink:   /:categories/:year/:month/:title/
timezone:    Asia/Yerevan
future:      true
highlighter: pygments
markdown:    kramdown
kramdown:
  auto_ids: false

