name: Александр Бизиков
description: Пишу об интересных и полезных для меня материалах
email: alexandr@bizikov.ru
age: 22
vk: http://vk.com/bizikov
twitter: http://twitter.com/bizi
instagram: http://instagram.com/bizikov
url: http://bizikov.ru
permalink: /:categories/:year/:month/:title/
paginate: 5
markdown: kramdown